# Generated by Django 4.0.3 on 2022-04-01 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0005_rename_password_utilisateur_mdp'),
        ('client', '0002_alter_client_utilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='utilisateur',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='utilisateur.utilisateur'),
        ),
    ]
