# Generated by Django 4.0.2 on 2022-02-26 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0003_utilisateur_sexe'),
        ('abonne', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonne',
            name='utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utilisateur.utilisateur'),
        ),
    ]
