# Generated by Django 4.0.2 on 2022-02-27 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0004_alter_utilisateur_cni_alter_utilisateur_email_and_more'),
        ('abonne', '0002_alter_abonne_utilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonne',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateur.utilisateur'),
        ),
    ]
