# Generated by Django 4.0.3 on 2022-03-31 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonne', '0003_alter_abonne_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonne',
            name='number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
