# Generated by Django 4.0.3 on 2022-04-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonne', '0004_abonne_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abonne',
            name='number',
        ),
        migrations.AddField(
            model_name='abonne',
            name='test',
            field=models.CharField(default='abonne', max_length=50),
        ),
    ]
