# Generated by Django 4.0.3 on 2022-04-01 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abonne', '0005_remove_abonne_number_abonne_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abonne',
            name='test',
        ),
    ]
