# Generated by Django 4.0.3 on 2022-04-01 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0005_rename_password_utilisateur_mdp'),
        ('abonne', '0006_remove_abonne_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonne',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='utilisateur.utilisateur'),
        ),
    ]
