# Generated by Django 4.0.2 on 2022-02-22 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='sexe',
        ),
    ]
