# Generated by Django 4.0.2 on 2022-02-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0002_remove_utilisateur_sexe'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='sexe',
            field=models.CharField(choices=[('masculin', 'masculin'), ('feminin', 'feminin')], max_length=100, null=True),
        ),
    ]
