# Generated by Django 4.0.3 on 2022-03-22 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0004_alter_utilisateur_cni_alter_utilisateur_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='password',
            new_name='mdp',
        ),
    ]
