# Generated by Django 4.0.3 on 2022-04-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0005_rename_password_utilisateur_mdp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='login',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='password',
            field=models.CharField(default=5, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
