# Generated by Django 4.0.3 on 2022-04-05 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0006_remove_utilisateur_login_utilisateur_last_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='password',
        ),
    ]
