# Generated by Django 4.0.3 on 2022-04-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0007_remove_utilisateur_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
