# Generated by Django 4.0.2 on 2022-02-27 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abonne', '0003_alter_abonne_utilisateur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_boite', models.CharField(max_length=100, null=True)),
                ('descrition_boite', models.CharField(max_length=100, null=True)),
                ('ninea_boite', models.IntegerField(null=True)),
                ('image', models.ImageField(default=False, upload_to='pics')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('abonne', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='abonne.abonne')),
            ],
        ),
    ]
