# Generated by Django 4.0.2 on 2022-02-28 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boite',
            old_name='abonne',
            new_name='id_abonne',
        ),
        migrations.AlterField(
            model_name='boite',
            name='descrition_boite',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='boite',
            name='nom_boite',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
