# Generated by Django 4.0.2 on 2022-02-28 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boite', '0002_rename_abonne_boite_id_abonne_and_more'),
        ('localisation', '0001_initial'),
        ('rubrique', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_service', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('id_boite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boite.boite')),
                ('id_localisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='localisation.localisation')),
                ('id_rubrique', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rubrique.rubrique')),
            ],
        ),
    ]
