# Generated by Django 4.0.2 on 2022-02-28 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paiement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_credit', models.IntegerField(null=True)),
                ('etat', models.BooleanField(null=True)),
                ('id_paiement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='paiement.paiement')),
            ],
        ),
    ]
