# Generated by Django 4.0.2 on 2022-02-28 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.CharField(max_length=200, null=True)),
                ('nom_pub', models.CharField(max_length=100, null=True)),
                ('date_debut', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_fin', models.DateTimeField(auto_now_add=True, null=True)),
                ('id_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service')),
            ],
        ),
    ]
