# Generated by Django 4.0.2 on 2022-02-28 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(max_length=50, null=True)),
                ('commune', models.CharField(max_length=200, null=True)),
                ('latitude', models.BigIntegerField(null=True)),
                ('longitude', models.BigIntegerField(null=True)),
            ],
        ),
    ]
