# Generated by Django 4.0.3 on 2022-03-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localisation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localisation',
            name='commune',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='localisation',
            name='latitude',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='localisation',
            name='longitude',
            field=models.IntegerField(null=True),
        ),
    ]
