# Generated by Django 4.0.2 on 2022-02-28 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boite', '0002_rename_abonne_boite_id_abonne_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_pack', models.CharField(max_length=50, null=True)),
                ('prix_pack', models.IntegerField(null=True)),
                ('nombre_credit', models.IntegerField(null=True)),
                ('duree', models.IntegerField(null=True)),
                ('id_boite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boite.boite')),
            ],
        ),
    ]
